label: crdp

deployment:

  name: crdp-deployment
  crdpContainername: crdp-container
  crdpimage: thalesciphertrust/ciphertrust-restful-data-protection:latest
  replicas: 1 
 
env:
  serverMode: no-tls
  kms: 127.0.0.1 
  regToken: 123456789

service:
  name: crdp-service
  type: NodePort
  nodePort: 32082 # This value can be any number between 30000-32767
  port: 8090
  probesPort: 8080
  nodePortForProbes: 32080 # This value can be any number between 30000-32767

